### ISSUE TITLE
Mail pour les participants

### ISSUE THREAD

**Issue by SebastienBoutry** [davidcarayon/Mondial_2018#13]
On met quoi ????

-le répertoire de dépôt
-l'information d'une relance tous les lundis pour les pronos
....

**Comment by davidcarayon** [comment]
- Répertoire de dépôt
- Info de relance
+ Rappel du site (pour ceux qui se sont inscrits par mail direct) ?
+ Liens vers les résultats ?

**Comment by SebastienBoutry** [comment]
- En cas d'absence (terrain), on accepte (ou j'accepte de recevoir un mail) les mails avec le fichier pronostics 
- Avatar
-Objet à mettre dans le mail Zabivaka Challenge

**Comment by tleboucher** [comment]
Mails envoyés. Calendrier des mails à envoyer et qui les envoie pendant le mondial est sur le tableau de Marie et David. Je prépare tous les mails demain.
