### ISSUE TITLE
Script bug encoding

### ISSUE THREAD

**Issue by SebastienBoutry** [davidcarayon/Mondial_2018#15]
iconv(table_pays[[col]], "latin1", "UTF-8")

Afin de modifier les encoding dans mon script j'ai mis cela mais si l'encoding est deja bon il détruit le boulot.
Donc il faut faire attention avec cela 

Seb

**Comment by SebastienBoutry** [comment]
- enlever les accents sur les tables

**Comment by tleboucher** [comment]
Tous les accents ont été enlevé ! Et l'iconv enlevé
