### ISSUE TITLE
"Pot Mondial"

### ISSUE THREAD

**Issue by mariewach** [davidcarayon/Mondial_2018#17]
Pour anticiper la fin du mondial, et permettre au plus grand nombre de participants au projet pronostics Russie_2018 d'être présent au pot de fin du mondial, il faudrait penser d'ici quelques jours à faire un doodle et bloquer une date..? car il y a les vacances apres...?

**Comment by SebastienBoutry** [comment]
yes mais je pensais voir selon seulement nous et fixer une date

**Comment by tleboucher** [comment]
Je préparerai le mail, on décide de la date demain (14/06) ? 

Je prépose Seb à l'organisation du pot :D

**Comment by SebastienBoutry** [comment]
Il faudra communiquer sur la date du pot !!!

**Comment by tleboucher** [comment]
Je prépare justement le prochain mail et j'en parle dedans
