### ISSUE TITLE
Packages à installer

### ISSUE THREAD

**Issue by SebastienBoutry** [davidcarayon/Mondial_2018#19]
plotly

**Comment by davidcarayon** [comment]
Est-ce que tu pourrais éditer ton premier message pour avoir une liste complète des packages sous cette forme ? Comme ça, on exécute la commande avant de lancer le bash pour tester. Et le mettre à jour dès l'ajout d'un nouveau package ?
```
list_packages < c("tidyverse","lubridate","purrr","Hmisc","RColorBrewer")
sapply(list_packages, library, character.only = TRUE)
```
Merci !

**Comment by tleboucher** [comment]
Je voulais justement ouvrir cette issue ! Marie et Séb, quand vous faites un graphe, pensez à ajouter ici tous les packages que vous utilisez pour que le script ne plante pas pour David ou moi !

**Comment by mariewach** [comment]
"ggpubr" à ajouter aussi

**Comment by SebastienBoutry** [comment]
```
list_packages <-c("ggthemes","circlepackeR","Hmisc","echarts4r","magrittr","data.tree","flexdashboard","ggplot2","googleVis","ggflags","scales","formattable","kableExtra","lubridate","timevis","tidyverse","flexdashboard","lubridate","googleVis","ggpubr","gganimate","tweenr","viridis","animation","slickR","svglite","htmlwidgets","plotly")
sapply(list_packages, library, character.only = TRUE)
```

**Comment by SebastienBoutry** [comment]
devtools::install_github('emitanaka/anicon')


list_packages <-c("ggthemes","circlepackeR","Hmisc","echarts4r","magrittr","data.tree","flexdashboard","ggplot2","googleVis","ggflags","scales","formattable","kableExtra","lubridate","timevis","tidyverse","flexdashboard","lubridate","googleVis","ggpubr","gganimate","tweenr","viridis","animation","slickR","svglite","htmlwidgets","plotly","anicon")
sapply(list_packages, library, character.only = TRUE)

**Comment by davidcarayon** [comment]
Il faut d'abord installer icon pour ceux qui ne l'ont pas, je l'ai pas trouvé sur le CRAN mais dispo ici : 
devtools::install_github("ropenscilabs/icon")

**Comment by SebastienBoutry** [comment]
install_github("treemap", username="mtennekes", subdir="pkg")
install_github("timelyportfolio/d3treeR")


library(treemap)
library(d3treeR)

**Comment by SebastienBoutry** [comment]
install.packages("rAmCharts")

install.packages("pipeR")
