### ISSUE TITLE
Script maître qui exécute la bancarisation et met à jour le site

### ISSUE THREAD

**Issue by davidcarayon** [davidcarayon/Mondial_2018#2]
Dossier contenant 
- un clone du github
- le dossier de travail.

Le script, en bash (.sh) doit : 
- `git pull origin master` pour mettre à jour le clone 
- `R CMD BATCH travail/R/*.R` pour exécuter les scripts qui mettent à jour le fichier de sortie Rdata dans travail
- `cp travail/sortie.RData git/data/sortie.RData` copie la sortie de travail dans le dossier git pour pouvoir actualiser le site
- `R CMD BATCH rmarkdown::render_site(git)`
- `git add .`
- `git commit -m "commit"`
- `git push origin master`

**Comment by davidcarayon** [comment]
Ok le script est fait : 

```
#!/bin/bash
rm -r Mondial_2018
git clone https://github.com/davidcarayon/Mondial_2018.git
R CMD BATCH travail/scripts/*.R
cp travail/sorties_tables Mondial_2018/sorties_table
R CMD BATCH render_site.R
cd Mondial_2018
git add .
git commit -m "updating website"
git push origin master
```
Je dois juste gérer de mon côté la connexion pc commun pour pouvoir faire du git dessus.
Éventuellement rajouter un `cp table_participants` si il est géré à part.

**Comment by davidcarayon** [comment]
Idéalement, ce script pourrait faire appel, dans sa première ligne, au script de @tleboucher qui transfère depuis le PC commun de stockage vers celui de travail. Une simple exécution de ce script pourrait donc récupérer les pronos, les traiter, et mettre à jour le site.

**Comment by davidcarayon** [comment]
MAJ :  Le bash a été testé sur les données factices et est OK. Il ne peut être exécuté que par un pinguin.

- Il rafraîchit le répertoire github
- Il  lance les scripts R comme il faut (il exécute les scripts 03 et 04 pour le moment, il vaut mieux procéder un par un, et il faudra adapter les deux autres si besoin par rapport au chemins relatifs)
- Puis il copie tout ce qui est dans "sorties_tables" dans le git Mondial_2018/data/sorties_tables
- Puis il render site
- Puis il push vers github

Le script : 

```
#!/bin/bash
cd Mondial_2018/
git pull origin
cd ..
R CMD BATCH travail/scripts/03_bancarisation_pronostics.R >log/log1.txt
R CMD BATCH travail/scripts/04_calcul_des_points.R >log/log2.txt
cp -r travail/sorties_tables/. Mondial_2018/data/sorties_tables/
R CMD BATCH render_site.R >log/log3.txt
cd Mondial_2018
git add .
git commit -m "updating website"
git push origin master
```

**Comment by tleboucher** [comment]
1er test demain (14/06) sur mon PC ?
