### ISSUE TITLE
Script de bancarisation / calcul de points

### ISSUE THREAD

**Issue by davidcarayon** [davidcarayon/Mondial_2018#4]
Le (ou les) scripts doivent lire :
- La base des tables de référence (.Rdata)
- Les nouveaux pronostics contenus dans les fichiers excels, avec les contrôles date qui vont bien
- La table des participants/cotisation pour mettre à jour le fichier .Rdata de sortie qui ira alimenter le site.

Puis, calculer les points selon les règles définies pour alimenter le .RData qui ira alimenter le site.

**Comment by SebastienBoutry** [comment]
J'ai commencé à faire la bancarisation pour les vrais résultats du mondial avec la gestion de penalty pour la phase d'élimination directe.
Pour les pronostics je laisse la main à Marie

**Comment by SebastienBoutry** [comment]
Ok c'est bon pour la table participants...il faut juste que je renomme correctement le Rdata

**Comment by tleboucher** [comment]
Je pense qu'on peut fermer ?
