### ISSUE TITLE
Onglet Mondial et Pronostics

### ISSUE THREAD

**Issue by SebastienBoutry** [davidcarayon/Mondial_2018#6]
Il me faudrait deux onglets pour pouvoir mettre les scripts R dans les bonnes parties
Merci par avance

**Comment by davidcarayon** [comment]
Sinon je te propose un menu déroulant pour les résultats, sur l'onglet actuel 'pronostics et résultats".
Derrière cet onglet, appelé "Résultats" tu aurais "Résultats du Mondial" et "Résultats des pronostics".

Est-ce que ça te va ? si oui, je renomme "Results.Rmd" en "results_mondial.Rmd" et je crée un "results_pronostics.Rmd"
