### ISSUE TITLE
Graphiques Pronostics

### ISSUE THREAD

**Issue by SebastienBoutry** [davidcarayon/Mondial_2018#8]
Propositions

-googleVis
-podium ggplot les trois premiers + photos (Marie penses tu qu'il est possible de déssiner un podium en ggplot geom_rect)

**Comment by mariewach** [comment]
Yes je vois ça assez simple de faire un podium avec ggplot2, parfait pour les graphiques, lundi je mets la publi de coté pour me reconcentrer sur le mondial!!
