### ISSUE TITLE
Script results_pronostics

### ISSUE THREAD

**Issue by SebastienBoutry** [davidcarayon/Mondial_2018#9]
Vite fait, Vendredi soir j'ai  essayé de lancer le script "results_pronostics", je me suis aperçu

- un bug d'interprétation (à vérifier) la différence de buts.
- le format des données Score

On pourra en discuter ...j'ai commencer à modifier certains scripts

**Comment by mariewach** [comment]
??? ca marchait très bien vendredi matin :( on revoit ca lundi alors

**Comment by SebastienBoutry** [comment]
Tu dois encore avoir un petit bug sur ta sortie car les points sont en chaines de caractères

**Comment by mariewach** [comment]
Probleme resolu, all good! merci Seb, j'ai sauvegardé la sortie
